steps:
  - name: "gcr.io/cloud-builders/kubectl"
    id: Deploy
    args:
      - "apply"
      - "-f"
      - "deployment.yaml"
    env:
      - "CLOUDSDK_COMPUTE_REGION=us-west2"
      - "CLOUDSDK_CONTAINER_CLUSTER=tf-cluster"
      