apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
  labels:
    app: demo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-deploy
  template:
    metadata:
      labels:
        app: demo-deploy
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      containers:
        - name: demo-deploy
          image: us-west2-docker.pkg.dev/dazzling-byway-418414/demo/develop:852697f384df18e2c3d7caf3085140811b7c069f
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"
            limits:
              memory: "8Gi"
              cpu: "2000m"
---
kind: Service
apiVersion: v1
metadata:
  name: demo-deploy
spec:
  selector:
    app: demo-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
