apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "qkqhro"
    networking.gke.io/managed-certificates: "qkqhro"
spec:
  defaultBackend:
    service:
      name: demo-deploy
      port:
        number: 80
---
# apiVersion: networking.gke.io/v1
# kind: ManagedCertificate
# metadata:
#   name: qkqhro
# spec:
#   domains:
#     - qkqhro.com